# Generated by Django 5.2.16 on 2026-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatterportTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matterport_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('source_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('local_path', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
